[package]
name = "hdd-recovery-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.11", features = ["derive", "string", "env"] }
env_logger = "0.10.0"
log = "0.4.19"
serde = { version = "1.0.169", features = ["derive"] }
serde_json = "1.0.100"
